<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Domain\IVisitor.cs" />
    <Compile Include="Domain\IElement.cs" />
    <Compile Include="Domain\ElementA.cs" />
    <Compile Include="Domain\ElementB.cs" />
    <Compile Include="Domain\ConcreteVisitor.cs" />
    <Compile Include="Program.cs" />
  </ItemGroup>
</Project> 